### ISSUE TITLE
Images not showing

### ISSUE THREAD

**Issue by AJuliette** [mawise/bookshelf#3]
<img width="730" alt="Screenshot 2024-08-13 at 19 09 17" src="https://github.com/user-attachments/assets/2316a7e8-a831-491f-a494-9b004d589863">

I downloaded books from this website: https://www.ebooksgratuits.com/ebooks.php

I checked into the "Calibre Library" and they had cover files:

<img width="335" alt="Screenshot 2024-08-13 at 19 12 02" src="https://github.com/user-attachments/assets/dbc324eb-3664-4a8d-bd63-3f394dcbed15">

**Comment by mawise** [comment]
It looks like you have `..` in your image path.  I added logic to exclude any `..` in the file path to avoid someone trying to access more than just the Calibre directory.  If you're just using it locally, you can comment out or remove this line: https://github.com/mawise/bookshelf/blob/f5d0f162e067c2eb9d368148934a382fba093e36/app.rb#L29

**Comment by AJuliette** [comment]
I'm sorry I'm confused, how should the path look like ? Why is there 'download' added in front of it ?

I tried with a non-relative path and it's still not working:

<img width="890" alt="Screenshot 2024-08-13 at 21 26 00" src="https://github.com/user-attachments/assets/8ea4f0ed-977f-4299-8142-5703c449bd3c">

**Comment by mawise** [comment]
I'm sorry, but not sure what else could be going wrong.  When you run the app, it should output logs to the terminal.  Those logs might give you more clues.  You could also see if you can open the cover image directly in your browser using the "file" scheme: `file:///Users/juliette/Calibre...`.  I did download a few of the books your referenced, and they worked for me so I don't think the issue is with the books.
